#!/bin/sh

## PATH

# Jetbrains Toolbox Apps
PATH="$PATH:~/.local/share/JetBrains/Toolbox/scripts"

# PostgreSQL
export PGDATA=/var/lib/postgres/data16
export LD_LIBRARY_PATH=/opt/postgresql16/lib
PATH=/opt/postgresql16/bin:$PATH

#pyenv
export PYENV_ROOT="$HOME/.pyenv"
PATH="$PYENV_ROOT/bin:$PATH"
export PATH

# Python
export PYTHONSTARTUP="$HOME/.config/python/startup.py"

## Settings

# Use bat as a colorizing pager for man
export MANPAGER="sh -c 'col -bx | bat -l man -p'"
export MANROFFOPT="-c"
